<a href="https://colab.research.google.com/github/SangBeom-Hahn/BOAZ/blob/main/imdb_%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 이것만 공부해도 nlp는 마스터
- https://huggingface.co/docs/datasets/v1.1.0/index.html

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [2]:
data, info = tfds.load("huggingface:adv_glue", with_info=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating validation examples...: 0 examples [00:00, ? examples/s]

Shuffling ~/tensorflow_datasets/adv_glue/adv_sst2/1.0.0.incomplete11LN45/adv_glue-validation.tfrecord*...:   0…

Dataset adv_glue downloaded and prepared to ~/tensorflow_datasets/adv_glue/adv_sst2/1.0.0. Subsequent calls will reuse this data.


In [ ]:
print(info)

tfds.core.DatasetInfo(
    name='adv_glue',
    full_name='adv_glue/adv_sst2/1.0.0',
    description="""
    Adversarial GLUE Benchmark (AdvGLUE) is a comprehensive robustness evaluation benchmark
    that focuses on the adversarial robustness evaluation of language models. It covers five
    natural language understanding tasks from the famous GLUE tasks and is an adversarial
    version of GLUE benchmark.
    """,
    config_description="""
    Adversarial version of SST-2.
                The Stanford Sentiment Treebank consists of sentences from movie reviews and
                human annotations of their sentiment. The task is to predict the sentiment of a
                given sentence. We use the two-way (positive/negative) class split, and use only
                sentence-level labels.
    """,
    homepage='https://adversarialglue.github.io/',
    data_path='~/tensorflow_datasets/adv_glue/adv_sst2/1.0.0',
    file_format=tfrecord,
    download_size=39.71 KiB,
    dataset_size

In [ ]:
# 오호라 역시 허깅페이스 튜토리얼처럼 딕셔너리로 되어있다.
for data in data.take(5):
  print(data)

AttributeError: ignored

In [ ]:
len(data)

1

### 따라서 다른 데이터 ㄱㄱ

In [2]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 431 kB 9.4 MB/s 
     |████████████████████████████████| 212 kB 37.3 MB/s 
     |████████████████████████████████| 115 kB 45.3 MB/s 
     |████████████████████████████████| 163 kB 50.3 MB/s 
     |████████████████████████████████| 127 kB 37.4 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [3]:
from datasets import load_dataset
dataset = load_dataset('glue', 'mrpc', split='train')

/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_deprecation.py:97: FutureWarning: Deprecated argument(s) used in 'dataset_info': token. Will not be supported from version '0.12'.
  warnings.warn(message, FutureWarning)


Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

Dataset glue downloaded and prepared to /root/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad. Subsequent calls will reuse this data.


In [5]:
len(dataset)

3668

In [6]:
dataset[0]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0}

In [7]:
dataset[0]["idx"]

0

In [8]:
for i in dataset["sentence1"]:
  print(i, '\n')

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Besides the fact that Americans want to be liked , she said , there is a " huge cost when world opinion is negative to the United States . 

John Logsdon , a board member , said that " human spaceflight had become a place where dissent was not welcome . " 

PC-related products were the strongest sector in July , with microprocessors up 5.6 % and DRAMs up 8.2 % from June , the industry group said . 

The Prime Ministers of China , Russia and four central Asian nations have met in Beijing and approved a budget for their regional security grouping . 

The two Democrats on the five-member FCC held a press conference to sway opinion against Powell and the two other Republicans on the panel . 

It will cost about $ 20,000 per eight-week course of treatment , comparable to other injected cancer therapies , a spokeswoman said . 

The OneNote note-taking tool is listed at £ 169.99 while the InfoPath XML ( Extensible Markup Language ) data gathering applicatio

In [4]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.9 MB 25.2 MB/s 
     |████████████████████████████████| 6.6 MB 49.7 MB/s 


In [5]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [6]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [7]:
def encode(examples):
  return tokenizer(examples['sentence1'], examples['sentence2'], truncation=True, padding='max_length')

In [8]:
dataset = dataset.map(encode, batched=True)

  0%|          | 0/4 [00:00<?, ?ba/s]

In [14]:
# 문장이 최대 길이를 잡아서 길면 짜르고 부족하면 0 패딩처리를 한다.
dataset[0]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0,
 'input_ids': [101,
  7277,
  2180,
  5303,
  4806,
  1117,
  1711,
  117,
  2292,
  1119,
  1270,
  107,
  1103,
  7737,
  107,
  117,
  1104,
  9938,
  4267,
  12223,
  21811,
  1117,
  2554,
  119,
  102,
  11336,
  6732,
  3384,
  1106,
  1140,
  1112,
  1178,
  107,
  1103,
  7737,
  107,
  117,
  7277,
  2180,
  5303,
  4806,
  1117,
  1711,
  1104,
  9938,
  4267,
  12223,
  21811,
  1117,
  2554,
  119,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,

## 이런 모양으로 만들어야 한다!!!

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models, preprocessing
import tensorflow_datasets as tfds
max_len = 200
n_words = 10000
dim_embedding = 256
EPOCHS = 20 
BATCH_SIZE =500

In [ ]:
def load_data():#load data
  (X_train, y_train), (X_test, y_test) = datasets.imdb.load_data(num_words=n_words) # 10000개의 단어로만 이루어진 리뷰다.
  # Pad sequences with max_len
  
  # 이미지는 다 784행인데 리뷰는 문장에 단어 개수가 다 다르니 최대 길이를 200으로 잡고 넘으면 지워버리고 부족하면 0으로 padding한다.
  X_train = preprocessing.sequence.pad_sequences(X_train, maxlen=max_len) 
  X_test = preprocessing.sequence.pad_sequences(X_test, maxlen=max_len)
  return (X_train, y_train), (X_test, y_test)

In [ ]:
(X_train, y_train), (X_test, y_test) = load_data()

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
X_train

array([[   5,   25,  100, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [ ]:
# ?????? -> 딕셔너리에서 str2int된 것만 뽑으려고 했다 근데 이상한 말 나옴
print(list(data["input_ids"] for data in dataset))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## 역시나 잘 안 되어서 허깅페이스 튜토리얼 따라하기

In [9]:
len(dataset)

3668

In [10]:
dataset = dataset.map(lambda examples: {'labels': examples['label']}, batched=True)

  0%|          | 0/4 [00:00<?, ?ba/s]

In [ ]:
dataset[0]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0,
 'input_ids': [101,
  7277,
  2180,
  5303,
  4806,
  1117,
  1711,
  117,
  2292,
  1119,
  1270,
  107,
  1103,
  7737,
  107,
  117,
  1104,
  9938,
  4267,
  12223,
  21811,
  1117,
  2554,
  119,
  102,
  11336,
  6732,
  3384,
  1106,
  1140,
  1112,
  1178,
  107,
  1103,
  7737,
  107,
  117,
  7277,
  2180,
  5303,
  4806,
  1117,
  1711,
  1104,
  9938,
  4267,
  12223,
  21811,
  1117,
  2554,
  119,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,

In [24]:
dataset[50]

{'input_ids': tensor([  101,  3728,  1104,  1103,  3243,  1455,  1118,  1103,  3703,  1107,
          1103,  2698,   118, 14366, 13912,  1127,  1207,  1106,  1103,  4765,
           119,   102,  3728,  1104,  1103,  3703,  3243,  1127,  1207,  1106,
          1103,  4765,  1112,  1218,   119,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,   

In [11]:
len(dataset)

3668

In [12]:
import torch
dataset.set_format(type='torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'labels'])
dataloader = torch.utils.data.DataLoader(dataset, batch_size = 3000)
next(iter(dataloader))

{'input_ids': tensor([[  101,  7277,  2180,  ...,     0,     0,     0],
         [  101, 10684,  2599,  ...,     0,     0,     0],
         [  101,  1220,  1125,  ...,     0,     0,     0],
         ...,
         [  101, 25010,  1105,  ...,     0,     0,     0],
         [  101,  1337,  3187,  ...,     0,     0,     0],
         [  101,  1252,  1268,  ...,     0,     0,     0]]),
 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'labels': tensor([1, 0, 1,  ..., 1, 1, 1])}

In [13]:
len(next(iter(dataloader))["input_ids"])

3000

In [33]:
next(iter(dataloader))["input_ids"]

tensor([[  101,  7277,  2180,  ...,     0,     0,     0],
        [  101, 10684,  2599,  ...,     0,     0,     0],
        [  101,  1220,  1125,  ...,     0,     0,     0],
        ...,
        [  101, 25010,  1105,  ...,     0,     0,     0],
        [  101,  1337,  3187,  ...,     0,     0,     0],
        [  101,  1252,  1268,  ...,     0,     0,     0]])

In [32]:
next(iter(dataloader))["labels"]

tensor([1, 0, 1,  ..., 1, 1, 1])

### 이제 이거로 훈련하면 됨!

#### 버전 1 텐서 to 리스트

In [14]:
X = next(iter(dataloader))["input_ids"].tolist()

In [15]:
y = next(iter(dataloader))["labels"].tolist()

In [57]:
X_train = X[:2500]

In [58]:
X_test = X[2500:]
y_train = y[:2500]
y_test = y[2500:]

In [33]:
X_train[0]

[101,
 7277,
 2180,
 5303,
 4806,
 1117,
 1711,
 117,
 2292,
 1119,
 1270,
 107,
 1103,
 7737,
 107,
 117,
 1104,
 9938,
 4267,
 12223,
 21811,
 1117,
 2554,
 119,
 102,
 11336,
 6732,
 3384,
 1106,
 1140,
 1112,
 1178,
 107,
 1103,
 7737,
 107,
 117,
 7277,
 2180,
 5303,
 4806,
 1117,
 1711,
 1104,
 9938,
 4267,
 12223,
 21811,
 1117,
 2554,
 119,
 102,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,

In [59]:
from tensorflow.keras import datasets, layers, models, preprocessing

max_len = 500 # 이거의 기준은 뭘까? -> 최대 길이로 무조건 맞춰야한다
n_words = 10000 # 이거 단어의 종류인데 모르는데..?
dim_embedding = 256
EPOCHS = 20 
BATCH_SIZE =500

# 이거를 하면 X_train[0]이 다 0이 된다?? 빼고 해보자 -> 근데 입력으로 넣을때 모델 입력이 200개라서 개수를 맞춰야함
# maxlen을 오류에 맞게 500으로 해주니 나온다?? 아마도 이걸 최대 길이가 500인가 보다!!
X_train = preprocessing.sequence.pad_sequences(X_train, maxlen=max_len, padding="post") 
X_test = preprocessing.sequence.pad_sequences(X_test, maxlen=max_len, padding="post")

In [60]:
# 왜 0으로 되지?
X_train[0]

array([ 1103,  7737,   107,   117,  1104,  9938,  4267, 12223, 21811,
        1117,  2554,   119,   102, 11336,  6732,  3384,  1106,  1140,
        1112,  1178,   107,  1103,  7737,   107,   117,  7277,  2180,
        5303,  4806,  1117,  1711,  1104,  9938,  4267, 12223, 21811,
        1117,  2554,   119,   102,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

## 에러 집합

1. 임베딩에서 에러남 -> 덴스로 바꿈
2. padding에서 에러남 -> maxlen 맞춤
3. 덴스로 바꾸니 pooling 안됨

In [72]:
def build_model(): 
  model = models.Sequential()
  model.add(layers.Dense(256, input_dim = max_len, activation='relu')) 
  # model.add(layers.Embedding(12521, dim_embedding, input_length=max_len)) 
  model.add(layers.Dropout(0.3))

  # model.add(layers.GlobalMaxPooling1D())
  model.add(layers.Dense(128, activation='relu')) 
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(1, activation='sigmoid'))  

  return model

In [73]:
model=build_model()
model.summary()
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"]) 

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 256)               128256    
                                                                 
 dropout_11 (Dropout)        (None, 256)               0         
                                                                 
 dense_12 (Dense)            (None, 128)               32896     
                                                                 
 dropout_12 (Dropout)        (None, 128)               0         
                                                                 
 dense_13 (Dense)            (None, 1)                 129       
                                                                 
Total params: 161,281
Trainable params: 161,281
Non-trainable params: 0
_________________________________________________________________


In [63]:
# 무조건 모델 fit에는 넘파이 배열이 들어가야 하나봐
import numpy as np

X_train = np.array(X_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
y_train = np.array(y_train)

In [74]:
score = model.fit(X_train, y_train, epochs= EPOCHS, \
                  batch_size = BATCH_SIZE,
                  validation_data = (X_test, y_test)) 

Epoch 1/20
5/5 [==============================] - 1s 56ms/step - loss: 836.8494 - accuracy: 0.5820 - val_loss: 257.7159 - val_accuracy: 0.6780
Epoch 2/20
5/5 [==============================] - 0s 16ms/step - loss: 591.6163 - accuracy: 0.5296 - val_loss: 164.4933 - val_accuracy: 0.6400
Epoch 3/20
5/5 [==============================] - 0s 21ms/step - loss: 424.8970 - accuracy: 0.5584 - val_loss: 169.9816 - val_accuracy: 0.6960
Epoch 4/20
5/5 [==============================] - 0s 17ms/step - loss: 314.2751 - accuracy: 0.6000 - val_loss: 107.6795 - val_accuracy: 0.6560
Epoch 5/20
5/5 [==============================] - 0s 17ms/step - loss: 265.3294 - accuracy: 0.5520 - val_loss: 80.3456 - val_accuracy: 0.5900
Epoch 6/20
5/5 [==============================] - 0s 17ms/step - loss: 194.6134 - accuracy: 0.5732 - val_loss: 70.2722 - val_accuracy: 0.6520
Epoch 7/20
5/5 [==============================] - 0s 17ms/step - loss: 155.6252 - accuracy: 0.5912 - val_loss: 55.7982 - val_accuracy: 0.6560
Ep

In [75]:
score = model.evaluate(X_test, y_test, batch_size=BATCH_SIZE)


print("\nTest score:", score[0])
print('Test accuracy:', score[1])

1/1 [==============================] - 0s 41ms/step - loss: 0.8540 - accuracy: 0.7040

Test score: 0.8540053367614746
Test accuracy: 0.7039999961853027
